name: CI

on:
  push:
    branches:
    - main
  pull_request:
    types: [ opened, edited, synchronize ]

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image and .tex
      run: | 
        docker build . --file Dockerfile --tag fungiwnl/tex
        docker run --volume $(pwd):/tmp fungiwnl/tex pdflatex cv.tex

  macos-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install docker # Taken from https://github.com/actions/virtual-environments/issues/1143#issuecomment-652264388
      run: |
        mkdir -p ~/.docker/machine/cache
        curl -Lo ~/.docker/machine/cache/boot2docker.iso https://github.com/boot2docker/boot2docker/releases/download/v19.03.12/boot2docker.iso
        brew install --cask virtualbox
        brew install docker docker-machine
        docker-machine create --driver virtualbox default
        docker-machine env default
    - name: Build the Docker image and .tex
      run: |
        eval "$(docker-machine env default)" 
        docker build . --file Dockerfile --tag fungiwnl/tex
        docker run --volume $(pwd):/tmp fungiwnl/tex pdflatex cv.tex
