name: CI

on: push

jobs:

  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fungiwnl/tex:$(date +%s)
    - uses: actions/checkout@v2
    - name: Build the .tex
      run: docker run \      
           --volume $(pwd):/tmp \
           fungiwnl/tex \
           pdflatex cv.tex
           
  macos-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fungiwnl/tex:$(date +%s)
    - name: Build the .tex
      run: docker run \      
           --volume $(pwd):/tmp \
           fungiwnl/tex \
           pdflatex cv.tex
